### ISSUE TITLE
Error during compilation.

### ISSUE THREAD

**Issue by Pirater12** [BernardoGiordano/GUI-Template-for-3DS-homebrews#1]
make[1]: *** [/c/Users/User/Desktop/pro_kartik/GUI-Template-for-3DS-homebrews-ma
ster/GUI-Template-for-3DS-homebrews-master.3dsx] Error 5
make: *** [build] Error 2

**Comment by BernardoGiordano** [comment]
Make sure you have all the required libs installed.

**Comment by Pirater12** [comment]
I have all the required libs

**Comment by BernardoGiordano** [comment]
you reach to compile 3dsx version at least?

**Comment by Pirater12** [comment]
yes

**Comment by BernardoGiordano** [comment]
Perfect. Readme says "**If you want to compile a .cia, just provide needed files by yourself and uncomment cia related lines into the makefile**."

I think you don't have a rsf template into your path. Use [this](https://github.com/Steveice10/buildtools/blob/master/3ds/template.rsf), call it cia.rsf and put it in assets folder

**Comment by Pirater12** [comment]
Uh nut i don't want a cia

**Comment by BernardoGiordano** [comment]
send me the whole log, starting from building process

**Comment by Pirater12** [comment]
C:\Users\User\Desktop\pro_kartik\GUI-Template-for-3DS-homebrews-master>make
graphics.c
arm-none-eabi-gcc -MMD -MP -MF /c/Users/User/Desktop/pro_kartik/GUI-Template-for
-3DS-homebrews-master/build/graphics.d -g -Wall -O2 -mword-relocations -fomit-fr
ame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/c/Users/
User/Desktop/pro_kartik/GUI-Template-for-3DS-homebrews-master/inc/include -I/c/d
evkitPro/libctru/include -I/c/devkitPro/portlibs/armv6k/include -I/c/devkitPro/p
ortlibs/3ds/include -I/c/Users/User/Desktop/pro_kartik/GUI-Template-for-3DS-home
brews-master/build -I-/c/Users/User/Desktop/pro_kartik/GUI-Template-for-3DS-home
brews-master/source -DARM11 -D_3DS -c /c/Users/User/Desktop/pro_kartik/GUI-Templ
ate-for-3DS-homebrews-master/source/graphics.c -o graphics.o
main.c
arm-none-eabi-gcc -MMD -MP -MF /c/Users/User/Desktop/pro_kartik/GUI-Template-for
-3DS-homebrews-master/build/main.d -g -Wall -O2 -mword-relocations -fomit-frame-
pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/c/Users/User
/Desktop/pro_kartik/GUI-Template-for-3DS-homebrews-master/inc/include -I/c/devki
tPro/libctru/include -I/c/devkitPro/portlibs/armv6k/include -I/c/devkitPro/portl
ibs/3ds/include -I/c/Users/User/Desktop/pro_kartik/GUI-Template-for-3DS-homebrew
s-master/build -I-/c/Users/User/Desktop/pro_kartik/GUI-Template-for-3DS-homebrew
s-master/source -DARM11 -D_3DS -c /c/Users/User/Desktop/pro_kartik/GUI-Template-
for-3DS-homebrews-master/source/main.c -o main.o
linking GUI-Template-for-3DS-homebrews-master.elf
built ... GUI-Template-for-3DS-homebrews-master.smdh
3dsxtool.exe crashes.. after which this error appears..
make[1]: *** [/c/Users/User/Desktop/pro_kartik/GUI-Template-for-3DS-homebrews-ma
ster/GUI-Template-for-3DS-homebrews-master.3dsx] Error 5
make: *** [build] Error 2

**Comment by BernardoGiordano** [comment]
weird, this seems to be a devkitpro error. I tried compiling the repo and it seems to work just fine.
